### ISSUE TITLE
AuthorizationFailed After Upgrading to Oauth2

### ISSUE THREAD

**Issue by doesdev** [minimul/quickbooks-ruby-base#7]
Hate to bother you with this but I'm stumped atm. I have updated the config as such:

```ruby
$qb_oauth_consumer = OAuth2::Client.new(QB_KEY, QB_SECRET, {
  :site            => "https://appcenter.intuit.com/connect/oauth2",
  :authorize_url   => "https://appcenter.intuit.com/connect/oauth2",
  :token_url       => "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
  :connection_opts => {}
})

Quickbooks::Base.configure do |c|
  c.persistent_token = 'token'
  c.persistent_refresh_token = 'secret'
  c.persistent_company_id = 'realm'
end
```

I also updated the auth callback as needed, and am getting back the token and refresh token as expected. After setting those on the `billing_user` that get's passed in to all the `Quickbooks::Base` calls I am getting an `AuthorizationFailed` message.

```ruby
current_billing_user.token = resp.token
current_billing_user.secret = resp.refresh_token
current_billing_user.realm = params['realmId']
```

Is there some other details I missed in the upgrade? I looked at the diffs of the changes to this gem and didn't see anything else missing, but may have overlooked something.

**Comment by minimul** [comment]
@doesdev I don't use this gem anymore and haven't used it for a long time. 

All my projects are switched over to [qbo_api](https://github.com/minimul/qbo_api).

That said, I did just release v2.1.0 based on this [PR](https://github.com/minimul/quickbooks-ruby-base/pull/6/commits). It should solve your problem.

**Comment by doesdev** [comment]
Thanks for replying, was able to get it straightened out.
